name: Auto Update Data

on:
  schedule:
    - cron: '0 16 * * *'  # 每天 UTC 16 点（北京时间 0 点）自动运行
  workflow_dispatch:      # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Run update script
        run: python fetch_logged_trend_data.py

      - name: Commit and Push if Changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/all_items.csv
          git diff --cached --quiet || (git commit -m "auto: update data on $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M (CST)')" && git push)
